site_name: API de Gestión de Estudiantes

theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Inicio: index.md
  - Autenticación: autenticacion.md
  - Endpoints: endpoints.md